import type { Product, Collection, Testimonial, Currency } from '../types'

// ─── Currency Config ──────────────────────────────────────────────────────────
export const currencies: Record<Currency, { symbol: string; rate: number }> = {
  USD: { symbol: '$', rate: 1 },
  AED: { symbol: 'AED ', rate: 3.67 },
  INR: { symbol: '₹', rate: 83.5 },
}

// ─── WhatsApp ─────────────────────────────────────────────────────────────────
export const WHATSAPP_NUMBER = '971555626108'
export const WHATSAPP_BASE = `https://wa.me/${WHATSAPP_NUMBER}`

// ─── Collections ─────────────────────────────────────────────────────────────
export const collections: Collection[] = [
  {
    id: '1',
    name: 'High Jewellery',
    description: 'Masterpieces of unparalleled artistry — each piece a testament to exceptional craftsmanship and rare stones.',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80',
    link: '/jewellery',
    itemCount: 48,
  },
  {
    id: '2',
    name: 'Certified Gemstones',
    description: 'Rare stones sourced from the world\'s finest mines, certified by GIA, IGI & SGL authorities.',
    image: 'https://images.unsplash.com/photo-1573408301155-0ab5b671f3f9?w=800&q=80',
    link: '/gemstones',
    itemCount: 120,
  },
  {
    id: '3',
    name: 'Pre-Owned Luxury',
    description: 'Authenticated pre-owned pieces from prestigious maisons — at exceptional value with full certification.',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80',
    link: '/pre-owned',
    itemCount: 35,
  },
  {
    id: '4',
    name: 'Bespoke Creations',
    description: 'Your vision, our mastery — custom jewellery crafted to perfection from concept to delivery.',
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&q=80',
    link: '/custom',
    itemCount: 0,
  },
]

// ─── Products ─────────────────────────────────────────────────────────────────
export const allProducts: Product[] = [
  // GEMSTONES
  {
    id: 'gem-001',
    name: 'Colombian Emerald',
    category: 'gemstone',
    subcategory: 'Emerald',
    price: 12500,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1573408301155-0ab5b671f3f9?w=900&q=90',
      'https://images.unsplash.com/photo-1594938298603-c8148c4b4288?w=900&q=90',
    ],
    description: 'A breathtaking 5.2ct Colombian emerald of exceptional clarity, exhibiting the coveted "jardin" characteristic of fine Colombian stones. Sourced directly from the Muzo Valley.',
    certification: { authority: 'GIA', number: 'GIA-5234891' },
    details: { weight: '5.20 ct', origin: 'Muzo Valley, Colombia', cut: 'Oval', clarity: 'Eye Clean', color: 'Vivid Green' },
    isAvailable: true,
    isFeatured: true,
    isNew: false,
  },
  {
    id: 'gem-002',
    name: 'Kashmir Sapphire',
    category: 'gemstone',
    subcategory: 'Sapphire',
    price: null,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=900&q=90',
      'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=900&q=90',
    ],
    description: 'An exceptional 3.8ct Kashmir sapphire with the legendary velvety cornflower blue color — among the most prized of all gemstones. Unheated, with strong fluorescence.',
    certification: { authority: 'IGI', number: 'IGI-7823451' },
    details: { weight: '3.80 ct', origin: 'Kashmir, India', cut: 'Cushion', clarity: 'VVS', color: 'Cornflower Blue' },
    isAvailable: true,
    isFeatured: true,
    isNew: true,
  },
  {
    id: 'gem-003',
    name: 'Burmese Ruby',
    category: 'gemstone',
    subcategory: 'Ruby',
    price: 22000,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4b4288?w=900&q=90',
    ],
    description: 'A magnificent 2.1ct unheated Burmese ruby displaying the coveted "pigeon blood" colour — the most sought-after in the world of coloured gemstones.',
    certification: { authority: 'GIA', number: 'GIA-9821344' },
    details: { weight: '2.10 ct', origin: 'Mogok, Myanmar', cut: 'Oval', clarity: 'Eye Clean', color: 'Pigeon Blood Red' },
    isAvailable: true,
    isFeatured: false,
    isNew: true,
  },
  {
    id: 'gem-004',
    name: 'Ceylon Sapphire',
    category: 'gemstone',
    subcategory: 'Sapphire',
    price: 9800,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1573408301155-0ab5b671f3f9?w=900&q=90',
    ],
    description: 'A stunning 4.1ct Ceylon sapphire with exceptional brilliance and a vivid royal blue colour, sourced from the gem fields of Sri Lanka.',
    certification: { authority: 'SGL', number: 'SGL-3421876' },
    details: { weight: '4.10 ct', origin: 'Ratnapura, Sri Lanka', cut: 'Oval', clarity: 'VS', color: 'Royal Blue' },
    isAvailable: true,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'gem-005',
    name: 'Tanzanite',
    category: 'gemstone',
    subcategory: 'Tanzanite',
    price: 6500,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=900&q=90',
    ],
    description: 'An exquisite 8.5ct tanzanite displaying rich trichroic colour shifting from deep violet-blue to burgundy. Found only in the shadow of Mount Kilimanjaro.',
    certification: { authority: 'IGI', number: 'IGI-5521983' },
    details: { weight: '8.50 ct', origin: 'Merelani Hills, Tanzania', cut: 'Cushion', clarity: 'Eye Clean', color: 'Vivid Violet-Blue' },
    isAvailable: true,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'gem-006',
    name: 'Pink Diamond',
    category: 'gemstone',
    subcategory: 'Diamond',
    price: null,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=900&q=90',
    ],
    description: 'An extraordinary 1.2ct Fancy Vivid Pink diamond of exceptional rarity. GIA certified with excellent cut grade, representing one of the rarest colour grades in existence.',
    certification: { authority: 'GIA', number: 'GIA-4567890' },
    details: { weight: '1.20 ct', origin: 'Argyle, Australia', cut: 'Pear', clarity: 'VS1', color: 'Fancy Vivid Pink' },
    isAvailable: true,
    isFeatured: false,
    isNew: true,
  },

  // JEWELLERY
  {
    id: 'jwl-001',
    name: 'Burmese Ruby Ring',
    category: 'jewellery',
    subcategory: 'Rings',
    price: 18500,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=900&q=90',
      'https://images.unsplash.com/photo-1569067236772-ebf4f1f4d18c?w=900&q=90',
    ],
    description: 'An extraordinary platinum ring featuring a 2.5ct unheated Burmese ruby, flanked by brilliant-cut diamonds in a classic halo setting. A statement of timeless elegance.',
    certification: { authority: 'GIA', number: 'GIA-9123456' },
    details: { weight: '2.50 ct', origin: 'Myanmar', cut: 'Oval', clarity: 'Eye Clean', color: 'Pigeon Blood Red', metal: 'Platinum 950', occasion: 'Engagement / Special Occasions' },
    isAvailable: true,
    isFeatured: true,
    isNew: false,
  },
  {
    id: 'jwl-002',
    name: 'Pink Diamond Pendant',
    category: 'jewellery',
    subcategory: 'Necklaces',
    price: null,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=900&q=90',
    ],
    description: 'An extraordinary 1.2ct Fancy Pink diamond pendant set in 18K rose gold with a pavé diamond surround. GIA certified with exceptional colour distribution.',
    certification: { authority: 'GIA', number: 'GIA-4567890' },
    details: { weight: '1.20 ct', cut: 'Pear', clarity: 'VS1', color: 'Fancy Vivid Pink', metal: '18K Rose Gold', occasion: 'Gala / Anniversary' },
    isAvailable: true,
    isFeatured: true,
    isNew: true,
  },
  {
    id: 'jwl-003',
    name: 'Sapphire Eternity Band',
    category: 'jewellery',
    subcategory: 'Rings',
    price: 8500,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1569067236772-ebf4f1f4d18c?w=900&q=90',
    ],
    description: 'An elegant eternity band featuring alternating Ceylon sapphires and brilliant-cut diamonds, channel-set in 18K white gold. Timeless sophistication.',
    certification: { authority: 'SGL', number: 'SGL-8834512' },
    details: { weight: '6.50 ct total', metal: '18K White Gold', occasion: 'Anniversary / Weddings' },
    isAvailable: true,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'jwl-004',
    name: 'Emerald Drop Earrings',
    category: 'jewellery',
    subcategory: 'Earrings',
    price: 14200,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=900&q=90',
    ],
    description: 'Exceptional drop earrings featuring matched pair Colombian emeralds totalling 4.8ct, suspended from diamond-set bails in platinum. A rare matched-pair find.',
    certification: { authority: 'IGI', number: 'IGI-6634821' },
    details: { weight: '4.80 ct pair', origin: 'Colombia', metal: 'Platinum 950', occasion: 'Gala / Formal Events' },
    isAvailable: true,
    isFeatured: false,
    isNew: true,
  },

  // HIGH JEWELLERY — replace image paths with actual files saved to /public/images/
  {
    id: 'jwl-005',
    name: 'Emerald & Diamond Link Necklace',
    category: 'jewellery',
    subcategory: 'Necklaces',
    price: null,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=900&q=90',
      'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=900&q=90',
    ],
    description: 'An extraordinary Art Deco-inspired necklace set in platinum, featuring emerald cabochons interspersed with baguette and brilliant-cut diamonds throughout an intricate octagonal link chain. Each Colombian emerald is individually selected for colour and lustre. A true museum-quality High Jewellery piece.',
    certification: { authority: 'GIA', number: 'GIA-HJ-5821' },
    details: { origin: 'Colombia', cut: 'Cabochon', color: 'Vivid Green', metal: 'Platinum 950', occasion: 'Gala / Black Tie' },
    isAvailable: true,
    isFeatured: true,
    isNew: true,
  },
  {
    id: 'jwl-006',
    name: 'Paraiba Tourmaline High Jewellery Suite',
    category: 'jewellery',
    subcategory: 'Sets',
    price: null,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=900&q=90',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=900&q=90',
    ],
    description: 'A breathtaking High Jewellery parure featuring a centrepiece Paraiba tourmaline pendant necklace, cocktail ring, and matching drop earrings. Set in 18K rose gold, accented with marquise and cushion-cut orange sapphires creating a dramatic chromatic contrast. The Paraiba tourmalines — rare and electric — are of exceptional neon-blue saturation.',
    certification: { authority: 'IGI', number: 'IGI-HJ-7732' },
    details: { origin: 'Brazil', cut: 'Oval', color: 'Neon Blue / Electric Teal', metal: '18K Rose Gold', occasion: 'Red Carpet / Private Collection' },
    isAvailable: true,
    isFeatured: true,
    isNew: true,
  },
  {
    id: 'jwl-007',
    name: 'Diamond & Paraiba Tourmaline Parure',
    category: 'jewellery',
    subcategory: 'Sets',
    price: null,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1573408301185-0ab5b671f3f9?w=900&q=90',
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=900&q=90',
    ],
    description: 'A spectacular High Jewellery parure in 18K white gold comprising a pavé diamond and Paraiba tourmaline necklace, wide-band diamond bracelet, cocktail ring, and oval pendant. Hundreds of brilliant-cut white diamonds frame each vivid Paraiba tourmaline of exceptional neon-blue saturation. One of the rarest gemstone combinations available anywhere in the world.',
    certification: { authority: 'GIA', number: 'GIA-HJ-9104' },
    details: { origin: 'Brazil / Mozambique', cut: 'Oval & Round Brilliant', color: 'Vivid Neon Blue & White', metal: '18K White Gold', occasion: 'State / Gala / Investment' },
    isAvailable: true,
    isFeatured: true,
    isNew: true,
  },

  // PRE-OWNED
  {
    id: 'pre-001',
    name: 'Cartier Love Bracelet',
    category: 'pre-owned',
    subcategory: 'Bracelets',
    price: 7200,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=900&q=90',
    ],
    description: 'Authentic pre-owned Cartier Love Bracelet in 18K yellow gold, size 17. Authenticated by our master gemologist with original papers and box. Excellent condition.',
    certification: { authority: null },
    details: { metal: '18K Yellow Gold', occasion: 'Daily / Special' },
    isAvailable: true,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'pre-002',
    name: 'Van Cleef Alhambra Necklace',
    category: 'pre-owned',
    subcategory: 'Necklaces',
    price: 4800,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=900&q=90',
    ],
    description: 'Iconic pre-owned Van Cleef & Arpels Vintage Alhambra necklace with malachite motifs in 18K yellow gold. Accompanied by full authentication documentation.',
    certification: { authority: null },
    details: { metal: '18K Yellow Gold', occasion: 'Daily / Evening' },
    isAvailable: true,
    isFeatured: false,
    isNew: false,
  },
]

// ─── Testimonials ─────────────────────────────────────────────────────────────
export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Arjun Mehta',
    location: 'Mumbai, India',
    text: 'The Colombian emerald I purchased exceeded every expectation. The GIA certification, the directness of communication, and exceptional quality made this the most significant jewellery investment of my life.',
    rating: 5,
    purchasedItem: 'Colombian Emerald 5.2ct',
  },
  {
    id: '2',
    name: 'Fatima Al-Hassan',
    location: 'Dubai, UAE',
    text: 'Hamlet Global crafted my bespoke engagement ring with such precision and elegance. The journey from design to delivery was handled with utmost professionalism. Truly a world-class experience.',
    rating: 5,
    purchasedItem: 'Custom Engagement Ring',
  },
  {
    id: '3',
    name: 'James Whitmore',
    location: 'London, United Kingdom',
    text: 'Having sourced gems from major auction houses worldwide, I can confidently say Hamlet Global offers exceptional quality at factory-direct pricing. Their Kashmir sapphire collection is unparalleled.',
    rating: 5,
    purchasedItem: 'Kashmir Sapphire 3.8ct',
  },
]

// ─── Trust Stats ──────────────────────────────────────────────────────────────
export const trustStats = [
  { label: 'Certified Stones', value: '500+' },
  { label: 'Countries Served', value: '50+' },
  { label: 'Years of Expertise', value: '15+' },
  { label: 'Satisfied Clients', value: '2,000+' },
]
